# # version: "3.8"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "6060:2000"
#     volumes:
#       - ./backend:/app/backend
#       - ./frontend:/app/frontend

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: apk-upload:latest
    ports:
      - "6060:2000" # Map host port 6060 to container port 2000
    volumes:
      - ./backend:/app/backend # Mount backend code to container
      - ./frontend:/app/frontend # Mount frontend code to container
      - ./backend/uploads:/app/backend/uploads # Persist uploads
      - ./backend/uploads.db:/app/backend/uploads.db # Persist the SQLite DB file

    restart: always # Restart the container if it crashes
    environment:
      NODE_ENV: production # You can adjust environment variables here
      DB_FILE_PATH: /app/backend/uploads.db # Path to your DB file if needed in your code