# version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:2000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
